name: frontend_spaceregis
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.11.2
  dio: ^5.9.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.9.0
  google_fonts: ^6.3.0
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  provider: ^6.1.5
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
